FROM python:3.11-slim

EXPOSE 5678

RUN pip install debugpy -t /tmp
CMD ["python", "/tmp/debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678"]
#-m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
