name: fastapidb-debug
networks:
  net:
    driver: bridge
services:
  debugpy:
    image: fastapi-debugpy
    networks:
      - net
    build:
      context: .
      dockerfile: ./Dockerfile.debugpy
    ports:
      - 5678:5678
    depends_on:
      - fastapidb
  fastapidb:
    image: fastapidb
    networks:
      - net
    build:
      context: .
      dockerfile: ./Dockerfile.poetry
    ##command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
