name: fastapidb-debug
services:
  fastapidb-poetry:
    profiles:
      - poetry
    image: fastapidb
    build:
      context: .
      dockerfile: ./Dockerfile.poetry
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678

  fastapidb-pip:
    profiles:
      - pip
    image: fastapidb
    build:
      context: .
      dockerfile: ./Dockerfile.pip
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678
